import type { RescueRung } from "./types";

export type MagicSentence = {
  id: string;
  frame: string;
  arabic: string;
  meaning: string;
  /** One-job English for a comprehension stall. Never a sentence explaining the grammar. */
  tinyClue: string;
  /** Spoken once when modeling this item, with {name} filled from the speaker. */
  modelClue?: string;
  /** Pointing, a name tag, or the scene already carries this meaning. */
  sceneCarriesMeaning: boolean;
  /** Speak modelClue / tinyClue once on first encounter, even if the scene helps. */
  tinyClueOnIntroduce: boolean;
  minHeardBeforeProduction: number;
  productionRequired: boolean;
  rescueSequence: RescueRung[];
  arabicNarrowing?: string;
  responseStarter?: string;
  fadedFrame?: string;
  whyKey?: string;
};

export const MAGIC_SENTENCES: Record<string, MagicSentence> = {
  as_salamu: {
    id: "as_salamu",
    frame: "as-salāmu ʿalaykum",
    arabic: "السلام عليكم",
    meaning: "A greeting",
    tinyClue: "Hello.",
    sceneCarriesMeaning: false,
    tinyClueOnIntroduce: true,
    minHeardBeforeProduction: 0,
    productionRequired: false,
    rescueSequence: ["tiny-clue"],
    whyKey: "greeting",
  },
  wa_alaykum: {
    id: "wa_alaykum",
    frame: "wa ʿalaykumu s-salām",
    arabic: "وعليكم السلام",
    meaning: "And peace be upon you",
    tinyClue: "Hello.",
    sceneCarriesMeaning: false,
    tinyClueOnIntroduce: false,
    minHeardBeforeProduction: 1,
    productionRequired: false,
    rescueSequence: ["tiny-clue", "response-starter"],
    responseStarter: "وَعَلَيْكُمُ…",
    whyKey: "greeting",
  },
  ana: {
    id: "ana",
    frame: "ana ______",
    arabic: "أنا ___",
    meaning: "I am ___",
    tinyClue: "You?",
    modelClue: "Me — {name}.",
    sceneCarriesMeaning: true,
    tinyClueOnIntroduce: true,
    minHeardBeforeProduction: 1,
    productionRequired: true,
    rescueSequence: ["contextual-cue", "tiny-clue", "response-starter"],
    arabicNarrowing: "أَنْتَ؟",
    responseStarter: "أَنَا…",
    whyKey: "ana",
  },
  huwa: {
    id: "huwa",
    frame: "huwa ______",
    arabic: "هو ___",
    meaning: "He is ___",
    tinyClue: "Him.",
    sceneCarriesMeaning: true,
    tinyClueOnIntroduce: false,
    minHeardBeforeProduction: 2,
    productionRequired: false,
    rescueSequence: ["contextual-cue", "tiny-clue"],
    whyKey: "ana",
  },
  wa_anta: {
    id: "wa_anta",
    frame: "wa anta?",
    arabic: "وأنت؟",
    meaning: "And you?",
    tinyClue: "You?",
    sceneCarriesMeaning: true,
    tinyClueOnIntroduce: false,
    minHeardBeforeProduction: 0,
    productionRequired: false,
    rescueSequence: ["contextual-cue", "tiny-clue"],
    arabicNarrowing: "أَنْتَ؟",
    whyKey: "ana",
  },
  ismi: {
    id: "ismi",
    frame: "ismī ______",
    arabic: "اسمي ___",
    meaning: "My name is ___",
    tinyClue: "Your name?",
    sceneCarriesMeaning: true,
    tinyClueOnIntroduce: false,
    minHeardBeforeProduction: 2,
    productionRequired: true,
    rescueSequence: ["contextual-cue", "arabic-narrowing", "tiny-clue", "response-starter"],
    arabicNarrowing: "اسمك…؟",
    responseStarter: "اسْمِي…",
    whyKey: "ismi",
  },
  ma_ismuka: {
    id: "ma_ismuka",
    frame: "mā ismuka?",
    arabic: "ما اسمك؟",
    meaning: "What's your name?",
    tinyClue: "Your name?",
    sceneCarriesMeaning: false,
    tinyClueOnIntroduce: false,
    minHeardBeforeProduction: 2,
    productionRequired: false,
    rescueSequence: ["contextual-cue", "arabic-narrowing", "tiny-clue"],
    arabicNarrowing: "اسمك…؟",
    whyKey: "ismi",
  },
  ahlan_ya: {
    id: "ahlan_ya",
    frame: "ahlan yā ______",
    arabic: "أهلاً يا ___",
    meaning: "Welcome, ___",
    tinyClue: "Hi.",
    sceneCarriesMeaning: true,
    tinyClueOnIntroduce: false,
    minHeardBeforeProduction: 1,
    productionRequired: false,
    rescueSequence: ["tiny-clue"],
    whyKey: "greeting",
  },
  tasharraftu: {
    id: "tasharraftu",
    frame: "tasharraftu",
    arabic: "تشرفت",
    meaning: "Pleased to meet you",
    tinyClue: "Nice to meet you.",
    sceneCarriesMeaning: true,
    tinyClueOnIntroduce: false,
    minHeardBeforeProduction: 1,
    productionRequired: false,
    rescueSequence: ["tiny-clue"],
    whyKey: "greeting",
  },
  ana_min: {
    id: "ana_min",
    frame: "ana min ______",
    arabic: "أنا من ___",
    meaning: "I'm from ___",
    tinyClue: "From?",
    modelClue: "Me — from {place}.",
    sceneCarriesMeaning: false,
    tinyClueOnIntroduce: true,
    minHeardBeforeProduction: 1,
    productionRequired: true,
    rescueSequence: ["contextual-cue", "tiny-clue", "response-starter"],
    arabicNarrowing: "مِنْ أَيْنَ؟",
    responseStarter: "أَنَا مِنْ…",
    whyKey: "min",
  },
  askunu_fi: {
    id: "askunu_fi",
    frame: "askunu fī ______",
    arabic: "أسكن في ___",
    meaning: "I live in ___",
    tinyClue: "Live?",
    sceneCarriesMeaning: false,
    tinyClueOnIntroduce: true,
    minHeardBeforeProduction: 1,
    productionRequired: true,
    rescueSequence: ["contextual-cue", "tiny-clue", "response-starter"],
    responseStarter: "أَسْكُنُ فِي…",
    whyKey: "min",
  },
  uhibbu_an: {
    id: "uhibbu_an",
    frame: "uḥibbu an ______",
    arabic: "أحب أن ___",
    meaning: "I like to ___",
    tinyClue: "Like?",
    sceneCarriesMeaning: false,
    tinyClueOnIntroduce: true,
    minHeardBeforeProduction: 1,
    productionRequired: true,
    rescueSequence: ["contextual-cue", "tiny-clue", "response-starter"],
    responseStarter: "أُحِبُّ أَنْ…",
    fadedFrame: "uḥibbu ______",
    whyKey: "uhibbu_an",
  },
  uridu: {
    id: "uridu",
    frame: "urīdu ______",
    arabic: "أريد ___",
    meaning: "I want ___",
    tinyClue: "Want?",
    sceneCarriesMeaning: true,
    tinyClueOnIntroduce: false,
    minHeardBeforeProduction: 1,
    productionRequired: true,
    rescueSequence: ["contextual-cue", "tiny-clue", "response-starter"],
    responseStarter: "أُرِيدُ…",
    whyKey: "uridu",
  },
  indi: {
    id: "indi",
    frame: "ʿindī ______",
    arabic: "عندي ___",
    meaning: "I have ___",
    tinyClue: "Have?",
    sceneCarriesMeaning: true,
    tinyClueOnIntroduce: false,
    minHeardBeforeProduction: 1,
    productionRequired: true,
    rescueSequence: ["contextual-cue", "tiny-clue", "response-starter"],
    responseStarter: "عِنْدِي…",
    whyKey: "indi",
  },
  lianna: {
    id: "lianna",
    frame: "liʾanna ______",
    arabic: "لأن ___",
    meaning: "because ___",
    tinyClue: "Why?",
    sceneCarriesMeaning: false,
    tinyClueOnIntroduce: true,
    minHeardBeforeProduction: 1,
    productionRequired: true,
    rescueSequence: ["contextual-cue", "tiny-clue", "response-starter"],
    responseStarter: "لِأَنَّ…",
    whyKey: "lianna",
  },
  la_afham: {
    id: "la_afham",
    frame: "lā afham",
    arabic: "لا أفهم",
    meaning: "I don't understand",
    tinyClue: "Don't understand.",
    sceneCarriesMeaning: false,
    tinyClueOnIntroduce: true,
    minHeardBeforeProduction: 0,
    productionRequired: false,
    rescueSequence: ["tiny-clue", "response-starter"],
    responseStarter: "لَا أَفْهَم",
  },
  ila_alliqa: {
    id: "ila_alliqa",
    frame: "ilā al-liqāʾ",
    arabic: "إلى اللقاء",
    meaning: "Until we meet",
    tinyClue: "Bye.",
    sceneCarriesMeaning: false,
    tinyClueOnIntroduce: true,
    minHeardBeforeProduction: 1,
    productionRequired: false,
    rescueSequence: ["tiny-clue", "response-starter"],
    responseStarter: "إِلَى اللِّقَاء",
    whyKey: "farewell",
  },
};

export function magicSentence(id: string) {
  if (id === "ana_ismi") return MAGIC_SENTENCES.ismi;
  return MAGIC_SENTENCES[id];
}
